### ISSUE TITLE
Should we just use Github for everything?

### ISSUE THREAD

**Issue by bhalothia** [TheRemoteLab/letsdevops#3]
Project management
Wiki
Issue tracking
Roadmap

And then integrate it with slack..that's it.

**Comment by bhalothia** [comment]
@TheRemoteLab/lets-devops

**Comment by johnharris85** [comment]
To begin with I don't see any issues with this, as it grows may need to branch out but MVP and all that ;)

**Comment by bhalothia** [comment]
Alright..using github for now. @TheRemoteLab/lets-devops
